config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'pages#index'
get 'about', to: 'pages#about'
resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pro = current_user
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    #the following line of code was added to show thw user's association with a created product
    @product.user = current_user
    if @product.save
      flash[:success]="Your information was successfully added."
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success]="Your changes were updated"
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success]="The information was successfully destroyed"
    redirect_to products_path(@product)
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:beginner, :intermediate, :advanced, :language)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Repolyser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-light bg-light">
      <li><%= link_to "Repolyser", root_path,class: "navbar-brand", id:"logo"%></li>
  <form class="form-inline">
    <%= link_to '<button class="btn btn-outline-primary" type="button">Add Repositories</button>'.html_safe, new_product_path %>
    <div style="padding-left: 10px;">
      <%= link_to '<button class="btn btn-outline-success" type="button">List Repositories</button>'.html_safe,products_path%>
    </div>
  </form>
  <ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <% if user_signed_in?%>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">You<span class="caret"></span></a>
    <% else %>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login/SignUp <span class="caret"></span></a>
    <%end%>
    <ul class="dropdown-menu">
    <% if user_signed_in? %>
      <li><%= link_to "Edit profile", edit_user_registration_path %></li>
    <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
    <% if user_signed_in? %>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% end %>
    </ul>
  </li>
</ul>
</nav>

  </head>

  <body>
    <% flash.each do |name,msg|%>
    <ul>
      <li><%= msg%></li>
    </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div style="margin: 100px auto;" align="center">
<p><font color="light blue"><em>Welcome to Repolyser, a web application designed to help students/developers get started with open source.</font></em></p>
<p><font color="light blue"><em>"Repolyser" word is basically a portmanteau of "Repository" and "Analyser", i.e a Repository Analyser.</font></em></p>


<p><font color="light blue">Getting started in open source is usually a great hurdle for new-comers. The sudden gush of new information and technicalities obfuscate most.</font></p>
<p><b>While contributing to a desired GitHub repository is the main pattern of open source, selecting correct organisation's repository w.r.t your skillset happens to be the most important part though.</b></p>
<p><b></em>Thus, Repolyser helps such new-comers in the following ways:</b></em></p>
<div ><font color="green">
<li>Help categorize the various repositories on the basis of their complexity</li>
<li>Guests can view the curated division created by experienced users who label them as: "Beginner","Intermediate" or "Advanced" w.r.t to their experience.</li>
<li>Guests can also view the details of the author who created the suggestion by clicking the "Show" button.</li>
<li>Finding a conducive repository written in the language of your choice becomes a lot easier with Repolyser.</li>
</font>
</div>
</div>

app/views/pages/index.html.erb
<div align="center" style="width:50%; margin:115px auto">
<% if user_signed_in?%>
<p>Hello <font color="red"><%= @pro.try(:username)%></font></p>
<% end %>
<h2>Welcome to Repolyser!!</h2>
<h3 style="margin:50px">
  <%= link_to 'About',about_path%>
</h3>
</div>

app/views/products/_form.html.erb
<%= form_for @product do |f|%>
<p>
  <b><%= f.label :beginner %></b>
  <%= f.text_field :beginner%>
</p>
<p>
  <b><%= f.label :intermediate %></b>
  <%= f.text_field :intermediate%>
</p>
<p>
  <b><%= f.label :advanced %></b>
  <%= f.text_field :advanced%>
</p>
<p>
  <b><%= f.label :language%></b>
  <%= f.text_field :language%>
</p>
<p>
  <di>
    <%= f.submit%>
  </div>
</p>
<% end %>
<% if @product.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@product.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @product.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/products/edit.html.erb
<div align="center">
<p style="margin:50px auto"><font size="5" color="light blue"><em>Edit the Form</em></font></p>
<%= render 'form' %>
</div>

app/views/products/index.html.erb
<div align="center" >
<p style="margin:50px auto"><font size="5" color="green"><em>Your List</em></font></p>
</div>
<body>
<table style="width:70%; margin: 115px auto;" cellspacing="30px" style="height:136px;">
  <tr>
    <th>Beginner</th>
    <th>Intermediate</th>
    <th>Advanced</th>
    <th>Language Used</th>
  </tr>
  <% @products.each do |product|%>
  <tr>
    <td><%= product.beginner%></td>
    <td><%= product.intermediate%></td>
    <td><%= product.advanced%></td>
    <td><%= product.language%></td>
    <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-xs btn-primary"%></td>
    <td><%= link_to 'Show', product_path(product), class: "btn btn-xs btn-primary"%></td>
    <td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Are you sure you want to delete the information?"}, class: "btn btn-xs btn-danger" %></td>
  </tr>
  <%end%>
</table>
<style>
  table, th, td{
  border: 2px solid blue;
  text-align: center;
}
</style>

</body>

app/views/products/new.html.erb
<div align="center">
<p style="margin:50px auto"><font size="5" color="light blue"><em>Add Repositories</em></font></p>
<%= render 'form'%>
</div>

app/views/products/show.html.erb
<p align="center" style="margin: 50px auto;"><font color="red"><em>The following information was added</em></font></p>

<body>
<div align="center">
<p>
  <b>Beginner:</b> <font color="green"><%= @product.beginner %></font>
</p>
<p>
  <b>Intermediate:</b> <font color="blue"><%= @product.intermediate %></font>
</p>
<p>
  <b>Advanced:</b> <font color="red"><%= @product.advanced %></font>
</p>
<p>
  <b>Language Used:</b><font color="purple"><%= @product.language%></font>
</p>
</div>
<p align="center" style="margin-top: 50px"><em><u><b>This repository was added by:</b></u></em></p>
  <div align="center">
    <p><b>Username:</b><font color="light blue"><%= @product.user.try(:username)%></font></p>
    <p><b>Email Address:</b><font color="light blue"><%= @product.user.try(:email)%></font></p>
  </div>
</body>